### PR TITLE
#10 Fix required console-service-provider version

### PR DESCRIPTION
**Pull request by maximkou**
This add fix for #10

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks @maximkou!

Btw, this project is abandoned - I've never actually used it, but your PR looks good and I wanted to keep it working for you :). If you - or anyone else - is interested in maintaining the project, let us know!

I'll create a release right now.

Cheers!

**Comment by weaverryan** [comment]
Ah, nevermind, there were never released yet for this library :/ - I won't start now (but if we have a proper maintainer, they could).

**Comment by maximkou** [comment]
@weaverryan, if not a secret, why project now is abandoned? There are best solutions?

**Comment by weaverryan** [comment]
Not that at all :). The original person who made this repository doesn't work at KnpLabs anymore and does different work. So, there simply isn't anyone to put in the work and maintain this.

**Comment by maximkou** [comment]
@weaverryan, thanks for the answer!

**Pull request merged**
